import contractConfig from "./auditRegistry.contract.json" with { type: "json" };

/** Generated by `npm run sync:audit-registry`; do not duplicate ABI fragments here. */
export const AUDIT_REGISTRY_CHAIN_ID = contractConfig.chainId;
export const DEFAULT_AUDIT_REGISTRY_ADDRESS = contractConfig.address;

// Version 1 is canonical, UTF-8 encoded JSON as produced by
// canonicalizeAuditPayload() in lib/auditRegistry.js.
export const AUDIT_HASH_SCHEME = 1;

export const OPPORTUNITY_KIND = Object.freeze({
  BUSINESS_PROBLEM: 0,
  OPEN_FUNDING: 1,
  FUNDING_REQUEST: 2,
});

export const AUDIT_REGISTRY_ABI = contractConfig.abi;

const envAddress = import.meta.env?.VITE_AUDIT_REGISTRY_ADDRESS?.trim() ?? "";

export const AUDIT_REGISTRY_ADDRESS = envAddress || DEFAULT_AUDIT_REGISTRY_ADDRESS;

export function getAuditRegistryAddress(explicitAddress = AUDIT_REGISTRY_ADDRESS) {
  const value = String(explicitAddress ?? "").trim();
  if (!/^0x[0-9a-fA-F]{40}$/.test(value) || /^0x0{40}$/i.test(value)) {
    throw new Error("AuditRegistry address is missing or invalid.");
  }
  return value;
}
